---
- name: restart php-fpm
  service:
    name: "{{ librenms_php_fpm_service_effective }}"
    state: restarted

- name: restart nginx
  service:
    name: "{{ librenms_nginx_service_name }}"
    state: restarted
