---
- name: Validate HAProxy configuration before restart
  command:
    argv:
      - haproxy
      - -c
      - -f
      - /etc/haproxy/haproxy.cfg
  changed_when: false
  listen: Restart HAProxy

- name: Restart HAProxy
  service:
    name: "{{ librenms_haproxy_service_name }}"
    state: restarted

- name: Restart Keepalived
  service:
    name: "{{ librenms_keepalived_service_name }}"
    state: restarted
