---
librenms_base_packages:
  - acl
  - ca-certificates
  - curl
  - fping
  - git
  - graphviz
  - imagemagick
  - lsb-release
  - mtr-tiny
  - nginx-full
  - nmap
  - php-cli
  - php-curl
  - php-fpm
  - php-gd
  - php-gmp
  - php-json
  - php-mbstring
  - php-mysql
  - php-snmp
  - php-xml
  - php-zip
  - python3-command-runner
  - python3-dotenv
  - python3-pip
  - python3-psutil
  - python3-pymysql
  - python3-redis
  - python3-setuptools
  - python3-systemd
  - rrdtool
  - rsync
  - snmp
  - snmpd
  - traceroute
  - unzip
  - wget
  - whois
  - chrony

librenms_db_packages:
  - mariadb-server
  - mariadb-client
  - python3-pymysql

librenms_galera_packages:
  - galera-4
  - rsync

librenms_redis_packages:
  - redis-server
  - redis-sentinel
  - python3-redis

librenms_gluster_packages:
  - glusterfs-server
  - glusterfs-client
  - xfsprogs

librenms_lb_packages:
  - haproxy
  - keepalived

librenms_mariadb_service_name: mariadb
librenms_mariadb_socket: /run/mysqld/mysqld.sock
librenms_mariadb_tuning_conf: /etc/mysql/mariadb.conf.d/60-librenms.cnf
librenms_galera_conf_path: /etc/mysql/conf.d/galera.cnf

librenms_nginx_service_name: nginx
librenms_nginx_conf_path: /etc/nginx/conf.d/librenms.conf
librenms_web_runtime_user: www-data
librenms_web_runtime_group: www-data

librenms_php_cli_ini_path: ""
librenms_php_fpm_ini_path: ""
librenms_php_fpm_pool_dir: ""
librenms_php_fpm_service_name: ""

librenms_redis_service_name: redis-server
librenms_redis_conf_path: /etc/redis/redis.conf
librenms_redis_sentinel_conf_path: /etc/redis/sentinel.conf
librenms_redis_sentinel_native_service_name: redis-sentinel

librenms_snmpd_service_name: snmpd
librenms_snmpd_conf_path: /etc/snmp/snmpd.conf
librenms_snmp_persistent_config_candidates:
  - /var/lib/net-snmp/snmpd.conf
  - /var/lib/snmp/snmpd.conf

librenms_haproxy_service_name: haproxy
librenms_keepalived_service_name: keepalived
librenms_glusterd_service_name: glusterd
