---
- name: Back up LibreNMS HA deployment data
  hosts: librenms_nodes:librenms_db:librenms_redis:lb_nodes:gluster_nodes:!maintenance_nodes
  become: true
  gather_facts: true
  roles:
    - role: backup
