---
- name: Run controlled LibreNMS HA failover tests
  hosts: librenms_nodes:librenms_db:librenms_redis:lb_nodes:!maintenance_nodes
  become: true
  gather_facts: true
  roles:
    - role: ha_failover_test
