---
- name: Verify production readiness requirements
  hosts: librenms_nodes:librenms_db:librenms_redis:lb_nodes:gluster_nodes:!maintenance_nodes:!decommission_nodes
  become: true
  gather_facts: true
  any_errors_fatal: true
  roles:
    - role: doctor
      vars:
        librenms_doctor_network_tcp_checks_enabled: >-
          {{ librenms_production_readiness_network_tcp_checks_enabled }}
    - role: production_readiness
