#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
TASKS_FILE="$ROOT_DIR/roles/production_readiness/tasks/main.yml"
VERIFIER_FILE="$ROOT_DIR/roles/production_readiness/files/librenms-production-readiness-evidence-verify.py"
DEFAULTS_FILE="$ROOT_DIR/roles/production_readiness/defaults/main.yml"
PLAYBOOK_FILE="$ROOT_DIR/playbooks/production-readiness.yml"
GLOBAL_DEFAULTS_FILE="$ROOT_DIR/roles/librenms_defaults/defaults/main.yml"

require_text() {
    local file="$1"
    local expected="$2"

    if ! grep -Fq -- "$expected" "$file"; then
        printf 'Missing expected production readiness evidence guardrail in %s: %s\n' \
            "$file" "$expected" >&2
        exit 1
    fi
}

require_text "$DEFAULTS_FILE" "librenms_production_readiness_write_evidence: true"
require_text "$GLOBAL_DEFAULTS_FILE" "librenms_production_profile: false"
require_text "$DEFAULTS_FILE" "librenms_production_profile | bool or librenms_manage_host_firewall | bool"
require_text "$DEFAULTS_FILE" "librenms_production_profile | bool and librenms_mode == 'ha'"
require_text "$DEFAULTS_FILE" "librenms_production_readiness_evidence_retention_days: 365"
require_text "$DEFAULTS_FILE" "librenms_production_readiness_evidence_max_age_seconds: 86400"
require_text "$DEFAULTS_FILE" "librenms_production_readiness_evidence_integrity_enabled: true"
require_text "$DEFAULTS_FILE" "librenms_production_readiness_evidence_hmac_enabled"
require_text "$DEFAULTS_FILE" "librenms_production_readiness_evidence_verifier_path"
require_text "$DEFAULTS_FILE" "librenms_production_readiness_require_recent_failover_evidence"
require_text "$DEFAULTS_FILE" "librenms_production_readiness_failover_evidence_max_age_days: 30"
require_text "$DEFAULTS_FILE" "librenms_production_readiness_require_failover_evidence_integrity"
require_text "$DEFAULTS_FILE" "librenms_production_readiness_max_failover_recovery_seconds"
require_text "$DEFAULTS_FILE" "librenms_production_readiness_max_database_restore_seconds: 1800"
require_text "$DEFAULTS_FILE" "librenms_production_readiness_require_scheduled_daily_backup"
require_text "$DEFAULTS_FILE" "librenms_production_readiness_require_status_alert_routing"
require_text "$DEFAULTS_FILE" "librenms_production_readiness_require_encrypted_vault"
require_text "$DEFAULTS_FILE" "librenms_production_readiness_secret_source: ansible_vault"
require_text "$DEFAULTS_FILE" "librenms_production_readiness_external_secret_validation_command: []"
require_text "$TASKS_FILE" "Create controller-side production readiness evidence directory"
require_text "$TASKS_FILE" "Find expired production readiness evidence records"
require_text "$TASKS_FILE" "Write successful production readiness evidence"
require_text "$TASKS_FILE" "Build production readiness evidence identity"
require_text "$TASKS_FILE" "Require auditable production readiness identity"
require_text "$TASKS_FILE" "Require complete LibreNMS revision results"
require_text "$TASKS_FILE" "Require complete LibreNMS working-tree results"
require_text "$TASKS_FILE" "Query Ansible automation project revision"
require_text "$TASKS_FILE" "librenms_production_inactive_nodes"
require_text "$TASKS_FILE" "librenms_production_active_nodes"
require_text "$TASKS_FILE" "or (librenms_production_inactive_nodes | length) == 0"
require_text "$TASKS_FILE" "groups.get('maintenance_nodes', [])"
require_text "$TASKS_FILE" "groups.get('decommission_nodes', [])"
require_text "$TASKS_FILE" "librenms_db_mode == 'galera'"
require_text "$TASKS_FILE" "librenms_redis_mode == 'sentinel'"
require_text "$TASKS_FILE" "librenms_rrd_mode in ['glusterfs', 'external']"
require_text "$TASKS_FILE" "librenms_vip_enabled | bool"
require_text "$TASKS_FILE" "librenms_vip_ip | length > 0"
require_text "$TASKS_FILE" "librenms_galera_readiness_agent_enabled | bool"
require_text "$TASKS_FILE" "'evidence_schema_version': 1"
require_text "$TASKS_FILE" "'identity_version': 2"
require_text "$TASKS_FILE" "'db_mode': librenms_db_mode"
require_text "$TASKS_FILE" "'galera_cluster_name': librenms_galera_cluster_name"
require_text "$TASKS_FILE" "'tls_enabled': librenms_haproxy_tls_enabled"
require_text "$TASKS_FILE" "Require secure controller-side production readiness evidence verifier"
require_text "$TASKS_FILE" "Require secure production readiness evidence artifacts"
require_text "$TASKS_FILE" "'source_revision': librenms_production_readiness_source_revision"
require_text "$TASKS_FILE" "'automation_revision': librenms_production_readiness_automation_revision"
require_text "$TASKS_FILE" "'inventory_fingerprint': librenms_production_readiness_inventory_fingerprint"
require_text "$TASKS_FILE" "'host_firewall_verified':"
require_text "$TASKS_FILE" "'status_alert_routing_verified':"
require_text "$TASKS_FILE" "'inactive_nodes': librenms_production_inactive_nodes"
require_text "$TASKS_FILE" "Calculate generated production readiness evidence SHA-256 checksum"
require_text "$TASKS_FILE" "Write production readiness evidence checksum sidecar"
require_text "$TASKS_FILE" "Verify production readiness evidence checksum sidecar"
require_text "$TASKS_FILE" "production-readiness-*.json.sha256"
require_text "$TASKS_FILE" "Calculate authenticated production readiness evidence digest"
require_text "$TASKS_FILE" "Write authenticated production readiness evidence sidecar"
require_text "$TASKS_FILE" "Recalculate authenticated production readiness evidence digest after write"
require_text "$TASKS_FILE" "Require authenticated production readiness evidence sidecar matches"
require_text "$TASKS_FILE" "librenms_production_readiness_evidence_hmac_after_write.stdout"
require_text "$TASKS_FILE" "not ((librenms_mode == 'ha') or (librenms_production_profile | bool))"
require_text "$TASKS_FILE" "Install controller-side production readiness evidence verifier"
require_text "$TASKS_FILE" "Verify generated production readiness evidence with controller verifier"
require_text "$TASKS_FILE" "--source-revision"
require_text "$TASKS_FILE" "--automation-revision"
require_text "$TASKS_FILE" "--inventory-fingerprint"
require_text "$TASKS_FILE" "--max-age-seconds"
require_text "$TASKS_FILE" "--app-key-stdin"
require_text "$TASKS_FILE" "stdin_add_newline: false"
require_text "$TASKS_FILE" "production-readiness-*.json.hmac"
require_text "$TASKS_FILE" "Build production readiness evidence artifact list"
require_text "$TASKS_FILE" "librenms_production_readiness_evidence_artifacts | default([])"
require_text "$TASKS_FILE" "Publish production readiness result for controller job records"
require_text "$TASKS_FILE" "Find recent successful HA failover drill evidence"
require_text "$TASKS_FILE" "Require HA failover drill evidence checksum"
require_text "$TASKS_FILE" "Require HA failover drill evidence checksum matches"
require_text "$TASKS_FILE" "Require the recent HA failover drill covers essential cases"
require_text "$TASKS_FILE" "librenms_production_latest_failover_evidence.mode"
require_text "$TASKS_FILE" "librenms_production_latest_failover_evidence.vip"
require_text "$TASKS_FILE" "librenms_production_latest_failover_evidence.elapsed_seconds"
require_text "$TASKS_FILE" "failover_recovery_objective_seconds"
require_text "$TASKS_FILE" "Inspect scheduled daily backup timer health"
require_text "$TASKS_FILE" "Require scheduled daily backup health"
require_text "$TASKS_FILE" "--property=LoadState"
require_text "$TASKS_FILE" "librenms_production_daily_backup_timer.rc == 0"
require_text "$TASKS_FILE" "librenms_production_daily_backup_service.stdout_lines[0] == 'loaded'"
require_text "$TASKS_FILE" "librenms_production_daily_backup_service.stdout_lines[2] == 'success'"
require_text "$TASKS_FILE" "Require disposable database restore verification within its objective"
require_text "$TASKS_FILE" "database_restore_elapsed_seconds"
require_text "$TASKS_FILE" "librenms_production_validate.rc != 0"
require_text "$TASKS_FILE" "Require safe production backup manifest and artifact filenames"
require_text "$TASKS_FILE" "librenms_backup_manifest_filename is match"
require_text "$TASKS_FILE" "librenms_production_database_backup_stat.stat.isreg"
require_text "$TASKS_FILE" "librenms_status_alert_webhook_url | default('')"
require_text "$TASKS_FILE" "librenms_status_alert_webhook_validate_certs | default(true)"
require_text "$TASKS_FILE" "Require a declared production secret source"
require_text "$TASKS_FILE" "librenms_production_profile | bool and librenms_mode == 'ha'"
require_text "$TASKS_FILE" "librenms_host_firewall_management_sources | length"
require_text "$TASKS_FILE" "librenms_host_firewall_cluster_sources | length"
require_text "$TASKS_FILE" "or librenms_haproxy_tls_enabled | bool"
require_text "$TASKS_FILE" "Verify external production secret provider access"
require_text "$TASKS_FILE" "expand_argument_vars: false"
require_text "$TASKS_FILE" "Require an encrypted Ansible Vault secret file for production"
require_text "$TASKS_FILE" ".startswith('\$ANSIBLE_VAULT;')"
require_text "$TASKS_FILE" "or (librenms_production_profile | bool)"
require_text "$TASKS_FILE" "or (librenms_production_readiness_require_encrypted_vault | bool)"
require_text "$VERIFIER_FILE" "EVIDENCE_SCHEMA_VERSION = 1"
require_text "$VERIFIER_FILE" "require_regular_file"
require_text "$VERIFIER_FILE" "must be a regular file and not a symlink"
require_text "$VERIFIER_FILE" "HA_REQUIRED_BOOLEAN_FIELDS"
require_text "$VERIFIER_FILE" "inventory_fingerprint"
require_text "$VERIFIER_FILE" "automation_revision"
require_text "$VERIFIER_FILE" "application_nodes"
require_text "$VERIFIER_FILE" "host_firewall_verified"
require_text "$VERIFIER_FILE" "status_alert_routing_verified"
require_text "$VERIFIER_FILE" "inactive_nodes"
require_text "$VERIFIER_FILE" "required=True"
require_text "$PLAYBOOK_FILE" "!maintenance_nodes:!decommission_nodes"

doctor_offset="$(grep -nF -- "- role: doctor" "$PLAYBOOK_FILE" | head -n 1 | cut -d: -f1)"
readiness_offset="$(grep -nF -- "- role: production_readiness" "$PLAYBOOK_FILE" | head -n 1 | cut -d: -f1)"
[ -n "$doctor_offset" ] && [ -n "$readiness_offset" ] && [ "$doctor_offset" -lt "$readiness_offset" ] || {
    printf 'Production readiness evidence must run after the live Doctor network checks.\n' >&2
    exit 1
}

printf 'Production readiness evidence guardrail test passed.\n'
